#include <stdio.h>
#include "lexerDef.h"
#include "lexer.h"
#include <time.h>
// #include "parser.h"
// #include "parserDef.h"

void runLexer()
{
}

void runCompleteCode()
{
}

void printCommentFreeCode()
{
    removeComments();
}

void calculateRunTime()
{
    clock_t start_time, end_time;

    double total_CPU_time, total_CPU_time_in_seconds;

    start_time = clock();

    runCompleteCode();

    end_time = clock();

    total_CPU_time = (double)(end_time - start_time);

    total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

    printf("Code execution completed!\n\n");
    printf("Total CPU time: %d\n", total_CPU_time);
    printf("Total CPU time in seconds: %d\n", total_CPU_time_in_seconds);

}

int main()
{
    printf("Hey there!\nWelcome\n\n");

    printf("(a) Both lexer and syntax analysis module implemented\n(b) First and Follow set automated\n(c) Filling of Parse Table automated\n");

    while (1)
    {
        printf("Instructions: Press\n");
        printf("0 : For exit\n");
        printf("1 : For removal of comments and print the comment free code on the console.\n");
        printf("2 : For printing the token list generated by the lexer.\n");
        printf("3 : For parsing to verify the syntactic correctness of the input source code and printing the parse tree\n");
        printf("4 : For printing the total time taken by the code to run\n\n");

        int input;
        printf("Enter the input: ");
        scanf("%d", input);

        int quit = 0;

        switch (input)
        {
        case 0:
            quit = 1;
            break;

        case 1:
            runLexer();
            break;

        case 2:
            printCommentFreeCode();
            break;

        case 3:
            runCompleteCode();
            break;

        case 4:
            calculateRunTime();
            break;
        }

        if (quit)
        {
            break;
        }
    }

    printf("\n\nThank you for using our compiler\nHave a good day!");
}